name = "location"
main = "./src/index.mjs"
compatibility_date = "2022-09-08"

[durable_objects]
bindings = [{name = "LOCATION", class_name = "Location"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Location"]